# Overlay the pinned loader without modifying the dependency checkout.
enable_language(ASM)
execute_process(COMMAND xcrun -sdk macosx --show-sdk-version OUTPUT_VARIABLE METAL_SDK_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
if(METAL_SDK_VERSION VERSION_LESS 26.0)
  message(FATAL_ERROR "Xcode Metal SDK 26 or later is required to embed M5 tensor kernels")
endif()
file(READ "${LLAMA_SOURCE_DIR}/ggml/src/ggml-metal/ggml-metal-device.m" METAL_DEVICE_CODE)
set(EMBED_START [=[#if GGML_METAL_EMBED_LIBRARY
    GGML_LOG_INFO("%s: using embedded metal library\n", __func__);]=])
set(EMBED_END [=[#else
#ifdef SWIFT_PACKAGE]=])
string(FIND "${METAL_DEVICE_CODE}" "${EMBED_START}" EMBED_START_INDEX)
string(FIND "${METAL_DEVICE_CODE}" "${EMBED_END}" EMBED_END_INDEX)
if(EMBED_START_INDEX LESS 0 OR EMBED_END_INDEX LESS EMBED_START_INDEX)
  message(FATAL_ERROR "Pinned Metal loader boundaries changed; refusing unsafe runtime fallback")
endif()
string(SUBSTRING "${METAL_DEVICE_CODE}" 0 ${EMBED_START_INDEX} METAL_PREFIX)
string(SUBSTRING "${METAL_DEVICE_CODE}" ${EMBED_END_INDEX} -1 METAL_SUFFIX)
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/PrecompiledMetal.inc" METAL_LOADER)
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated")
set(METAL_OVERLAY "${CMAKE_BINARY_DIR}/generated/ggml-metal-device.m")
set(METAL_OVERLAY_CODE "#define GGML_METAL_EMBED_LIBRARY 1\n${METAL_PREFIX}${METAL_LOADER}${METAL_SUFFIX}")
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/PrecompiledTensorProbe.inc" METAL_PROBE_FUNCTION)
set(METAL_PROBE_DECL "ggml_metal_library_t ggml_metal_library_init_from_source(ggml_metal_device_t dev, const char * source, bool verbose) {")
string(FIND "${METAL_OVERLAY_CODE}" "${METAL_PROBE_DECL}" METAL_PROBE_INDEX)
foreach(PROBE IN ITEMS f16 bf16)
  set(PROBE_CALL "ggml_metal_library_init_from_source(dev, src_tensor_${PROBE}, false)")
  string(FIND "${METAL_OVERLAY_CODE}" "${PROBE_CALL}" PROBE_INDEX)
  if(PROBE_INDEX LESS 0 OR METAL_PROBE_INDEX LESS 0)
    message(FATAL_ERROR "Pinned tensor capability probes changed; refusing runtime source compilation")
  endif()
  if(PROBE STREQUAL "bf16")
    set(PROBE_TYPE true)
  else()
    set(PROBE_TYPE false)
  endif()
  string(REPLACE "${PROBE_CALL}" "local_ai_tensor_probe_from_data(dev, ${PROBE_TYPE})" METAL_OVERLAY_CODE "${METAL_OVERLAY_CODE}")
endforeach()
# The pinned source also exports a source compiler. Fail closed even if a future
# callsite unexpectedly reaches that API; all supported libraries are blobs.
string(FIND "${METAL_OVERLAY_CODE}" "${METAL_PROBE_DECL}" SOURCE_START)
string(FIND "${METAL_OVERLAY_CODE}" "void ggml_metal_library_free(ggml_metal_library_t lib) {" SOURCE_END)
if(SOURCE_START LESS 0 OR SOURCE_END LESS SOURCE_START)
  message(FATAL_ERROR "Pinned Metal source compiler boundaries changed")
endif()
string(SUBSTRING "${METAL_OVERLAY_CODE}" 0 ${SOURCE_START} SOURCE_PREFIX)
string(SUBSTRING "${METAL_OVERLAY_CODE}" ${SOURCE_END} -1 SOURCE_SUFFIX)
set(METAL_OVERLAY_CODE "${SOURCE_PREFIX}${METAL_PROBE_FUNCTION}${METAL_PROBE_DECL}\n    (void) dev; (void) source; (void) verbose;\n    return NULL;\n}\n\n${SOURCE_SUFFIX}")
string(FIND "${METAL_OVERLAY_CODE}" "static bool ggml_metal_library_compile_all(" COMPILE_START)
string(FIND "${METAL_OVERLAY_CODE}" "ggml_metal_library_t ggml_metal_library_init(ggml_metal_device_t dev) {" COMPILE_END)
if(COMPILE_START LESS 0 OR COMPILE_END LESS COMPILE_START)
  message(FATAL_ERROR "Pinned unused Metal compiler boundaries changed")
endif()
string(SUBSTRING "${METAL_OVERLAY_CODE}" 0 ${COMPILE_START} COMPILE_PREFIX)
string(SUBSTRING "${METAL_OVERLAY_CODE}" ${COMPILE_END} -1 COMPILE_SUFFIX)
set(METAL_OVERLAY_CODE "${COMPILE_PREFIX}${COMPILE_SUFFIX}")
file(WRITE "${METAL_OVERLAY}" "${METAL_OVERLAY_CODE}")
# llama_context uses this generic registration name for every backend. The pin's
# existing Metal setter otherwise remains unreachable through that interface.
file(READ "${LLAMA_SOURCE_DIR}/ggml/src/ggml-metal/ggml-metal.cpp" METAL_BACKEND_CODE)
set(METAL_PROC_START "static void * ggml_backend_metal_get_proc_address(ggml_backend_reg_t reg, const char * name) {")
string(FIND "${METAL_BACKEND_CODE}" "${METAL_PROC_START}" METAL_PROC_INDEX)
if(METAL_PROC_INDEX LESS 0)
  message(FATAL_ERROR "Pinned Metal proc-address entry changed")
endif()
string(REPLACE "${METAL_PROC_START}" "${METAL_PROC_START}\n    if (strcmp(name, \"ggml_backend_set_abort_callback\") == 0) {\n        return (void *)ggml_backend_metal_set_abort_callback;\n    }" METAL_BACKEND_CODE "${METAL_BACKEND_CODE}")
set(METAL_BACKEND_OVERLAY "${CMAKE_BINARY_DIR}/generated/ggml-metal.cpp")
file(WRITE "${METAL_BACKEND_OVERLAY}" "${METAL_BACKEND_CODE}")
get_target_property(METAL_SOURCES ggml-metal SOURCES)
set(METAL_KEPT_SOURCES "")
set(METAL_REPLACED_COUNT 0)
set(METAL_BACKEND_REPLACED_COUNT 0)
foreach(SOURCE IN LISTS METAL_SOURCES)
  get_filename_component(SOURCE_NAME "${SOURCE}" NAME)
  if(SOURCE_NAME STREQUAL "ggml-metal-device.m")
    math(EXPR METAL_REPLACED_COUNT "${METAL_REPLACED_COUNT}+1")
  elseif(SOURCE_NAME STREQUAL "ggml-metal.cpp")
    math(EXPR METAL_BACKEND_REPLACED_COUNT "${METAL_BACKEND_REPLACED_COUNT}+1")
    list(APPEND METAL_KEPT_SOURCES "${METAL_BACKEND_OVERLAY}")
  else()
    list(APPEND METAL_KEPT_SOURCES "${SOURCE}")
  endif()
endforeach()
if(NOT METAL_REPLACED_COUNT EQUAL 1 OR NOT METAL_BACKEND_REPLACED_COUNT EQUAL 1)
  message(FATAL_ERROR "Expected exactly one upstream Metal device and backend source")
endif()
set_property(TARGET ggml-metal PROPERTY SOURCES "${METAL_KEPT_SOURCES}")
set(METAL_DEFAULT "${CMAKE_BINARY_DIR}/bin/default.metallib")
set(METAL_TENSOR "${CMAKE_BINARY_DIR}/bin/ggml-tensor.metallib")
set(METAL_ASM "${CMAKE_BINARY_DIR}/generated/local-ai-metallib.s")
file(WRITE "${METAL_ASM}" ".section __DATA,__local_metal\n.p2align 4\n.globl _local_ai_default_metallib_start\n_local_ai_default_metallib_start:\n.incbin \"${METAL_DEFAULT}\"\n.globl _local_ai_default_metallib_end\n_local_ai_default_metallib_end:\n.p2align 4\n.globl _local_ai_tensor_metallib_start\n_local_ai_tensor_metallib_start:\n.incbin \"${METAL_TENSOR}\"\n.globl _local_ai_tensor_metallib_end\n_local_ai_tensor_metallib_end:\n")
set(PROBE_FILES "")
foreach(PROBE IN ITEMS f16 bf16)
  if(PROBE STREQUAL "bf16")
    set(PROBE_TYPE 1)
  else()
    set(PROBE_TYPE 0)
  endif()
  set(PROBE_AIR "${CMAKE_BINARY_DIR}/generated/tensor-${PROBE}-probe.air")
  set(PROBE_LIBRARY "${CMAKE_BINARY_DIR}/generated/tensor-${PROBE}-probe.metallib")
  add_custom_command(OUTPUT "${PROBE_LIBRARY}"
    COMMAND xcrun -sdk macosx metal -O3 -std=metal4.0 -mtargetos=macos26.0 -DLOCAL_AI_PROBE_BF16=${PROBE_TYPE} -c "${CMAKE_CURRENT_SOURCE_DIR}/TensorProbe.metal" -o "${PROBE_AIR}"
    COMMAND xcrun -sdk macosx metallib "${PROBE_AIR}" -o "${PROBE_LIBRARY}"
    DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/TensorProbe.metal" VERBATIM)
  list(APPEND PROBE_FILES "${PROBE_LIBRARY}")
  file(APPEND "${METAL_ASM}" ".p2align 4\n.globl _local_ai_${PROBE}_probe_start\n_local_ai_${PROBE}_probe_start:\n.incbin \"${PROBE_LIBRARY}\"\n.globl _local_ai_${PROBE}_probe_end\n_local_ai_${PROBE}_probe_end:\n")
endforeach()
add_custom_target(LocalAITensorProbeLibraries DEPENDS ${PROBE_FILES})
set_source_files_properties("${METAL_ASM}" PROPERTIES OBJECT_DEPENDS "${METAL_DEFAULT};${METAL_TENSOR};${PROBE_FILES}")
target_sources(ggml-metal PRIVATE "${METAL_OVERLAY}" "${METAL_ASM}")
target_include_directories(ggml-metal PRIVATE "${LLAMA_SOURCE_DIR}/ggml/src/ggml-metal")
add_dependencies(ggml-metal ggml-metal-lib)
add_dependencies(ggml-metal LocalAITensorProbeLibraries)

# Upstream eagerly constructs Metal while enumerating even a forced CPU run.
# Register it explicitly only after this worker's public GPU computation passes.
file(READ "${LLAMA_SOURCE_DIR}/ggml/src/ggml-backend-reg.cpp" REGISTRY_CODE)
set(AUTO_METAL_REG [=[#ifdef GGML_USE_METAL
        register_backend(ggml_backend_metal_reg());
#endif]=])
string(FIND "${REGISTRY_CODE}" "${AUTO_METAL_REG}" AUTO_METAL_INDEX)
if(AUTO_METAL_INDEX LESS 0)
  message(FATAL_ERROR "Pinned automatic Metal registration changed")
endif()
string(REPLACE "${AUTO_METAL_REG}" "// Metal is explicitly registered after the sandboxed public warmup." REGISTRY_CODE "${REGISTRY_CODE}")
set(REGISTRY_OVERLAY "${CMAKE_BINARY_DIR}/generated/ggml-backend-reg.cpp")
file(WRITE "${REGISTRY_OVERLAY}" "${REGISTRY_CODE}")
get_target_property(REGISTRY_SOURCES ggml SOURCES)
set(REGISTRY_KEPT_SOURCES "")
set(REGISTRY_REPLACED_COUNT 0)
foreach(SOURCE IN LISTS REGISTRY_SOURCES)
  get_filename_component(SOURCE_NAME "${SOURCE}" NAME)
  if(SOURCE_NAME STREQUAL "ggml-backend-reg.cpp")
    math(EXPR REGISTRY_REPLACED_COUNT "${REGISTRY_REPLACED_COUNT}+1")
  else()
    list(APPEND REGISTRY_KEPT_SOURCES "${SOURCE}")
  endif()
endforeach()
if(NOT REGISTRY_REPLACED_COUNT EQUAL 1)
  message(FATAL_ERROR "Expected exactly one upstream backend registry source")
endif()
set_property(TARGET ggml PROPERTY SOURCES "${REGISTRY_KEPT_SOURCES}")
target_sources(ggml PRIVATE "${REGISTRY_OVERLAY}")
target_include_directories(ggml PRIVATE "${LLAMA_SOURCE_DIR}/ggml/src")
