<Project>
  <PropertyGroup>
    <KalynaSigningCertificateThumbprint>2B0AF266FED001587A3BB460FCCC35EA94E3E57E</KalynaSigningCertificateThumbprint>
    <KalynaExpectedSignerSha256>7F38A06352123C3701BFD274531B0BB1D850BAC08F40F348E1E9B2C5A0C44ED6</KalynaExpectedSignerSha256>
    <KalynaExpectedSignerSha3_512>C3B852BD2D1EDBDC833AADD37080664E819AAD3F4A230D5CF40643197C36AA50F55E4216CEF13CB7A49995CF4566F7467C794D597D6CA0E899C97DE6600D5FE2</KalynaExpectedSignerSha3_512>
    <KalynaExpectedSignerSkein1024>DFF9A28BC4C2BC17B5B18FD026225A17EA981BFBE01B0FB52CFF767254AA2ACE3946AA323DBCA717E38DAA5481997FAB597642199B6A820660F273DFBCA9C50D8AB03D64CA9A8B9C35AC68B866CE73AC4C81E59682208D99584D526B9AB473220F37BB7CC39FC78EB5ECA98E0D8EE3BA76F61AE3D926B9C3C190C554F403C99B</KalynaExpectedSignerSkein1024>
    <KalynaExpectedMldsa87Sha256>FA55B69D11E20E7EC468DBE7570F88B7BA840BA9BEA11332F062214ADFEE39A1</KalynaExpectedMldsa87Sha256>
    <KalynaExpectedMldsa87Sha3_512>558B4CDEC4A1B3B50105C0C0A4EB14563E1287119BC781467D95B507CF0696576A299D8EBFB8EC6F866E4A9B460FF39CE375AAAA59C714C5C2B5441F33B31C12</KalynaExpectedMldsa87Sha3_512>
    <KalynaExpectedMldsa87Skein1024>4D8381E03EDA46D34C8B5771FA58258EBB11C5E056F73200B365F254B1CADDF78F672867CBA06781F5CE6A171F90FC20B99BA5DF01D043DD2F4DD29378094707247CB4DF516C1576C0250594CCEA0151B7B2A73BD93F57A1462A5D6649B363BF89A9249F6C83747782AE868B0D68F5B068575E368835340D828EAD38F0C4145A</KalynaExpectedMldsa87Skein1024>
  </PropertyGroup>
</Project>
